name: geoml-bld
# This is the recommended environment for building tigl from source
channels:
 - dlr-sc
 - nodefaults
dependencies:
 - cmake
#  - ninja=1.10.2                  # needed for the Ninja-based build instructions
 - pip                           # just make sure that pip installs into this env, if used
 - setuptools                    # needed to infer the python site-packages path
 - pythonocc-core
 - opencascade=7.6.2  
 - pytest
 - conda-forge::qt=5.15.8        # needed to build tiglviewer
 - python                        # needed to build python bindings
