[project]
name = "geoml"
version = "0.1.0"
description = "Central geometry library in C++ with python bindings."
readme = "README.md"
license = { text = "Apache-2.0" }
urls = { "homepage" = "https://github.com/DLR-SC/geoml" }
authors = [
    { name = "Reiswich Anton", email = "anton.reiswich@dlr.de" },
]
requires-python = ">=3.9"




[tool.pixi.workspace]
platforms = ["win-64", "linux-64", "osx-64"]
channels = ["dlr-sc", "dlr-sc/label/tigl-dev", "conda-forge"] 

channel-priority = "disabled" 

[tool.pixi.dependencies]
cmake = "*"
ninja = "*"
python = ">=3.9"
pip = "*"
pytest = "*"
pythonocc-core = "*"
swig = "*"
doxygen = "*"
sphinx-rtd-theme = "*"
breathe = "*"
sphinx = "*"
m2r = "*"
docutils = "<0.21"
#tk = ">=9.6.1,<10"
opencascade = "*" 

