name: "MacOS Tests"

description: "Test TiGL on MacOS"

inputs:

  build-artifact:
    description: "Name of the build artifact that contains the unit test binary."
    required: true

  unit-tests:
    description: "Set to true to run TiGLs unit tests (true or false)"
    required: false
    default: true

  api-tests:
    description: "Set to true to run geoml's api tests (true or false)"
    required: false
    default: true

  # integration-tests:
  #   description: "Set to true to run TiGLs integration tests (true or false)"
  #   required: false
  #   default: true

runs:

  using: "composite"
  
  steps:
  
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: tigl-bld
        environment-file: environment.yml
        auto-activate-base: false

    - name: Download built test directory
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}

    - name: extract build archive
      shell: bash
      run: |
        gtar -xzf build.tar.gz

    - name: Run unit tests
      if: ${{ inputs.unit-tests == 'true' }}
      shell: bash
      run: |
        cd build/tests/unittests/
        chmod a+x ./geoml-unittests
        ./geoml-unittests --gtest_shuffle --gtest_output=xml:unit_test_results.xml

    - name: Run api tests
      if: ${{ inputs.api-tests == 'true' }}
      shell: bash
      run: |
        cd build/tests/apitests/
        chmod a+x ./geoml-apitest
        ./geoml-apitest --gtest_shuffle --gtest_output=xml:unit_test_results.xml

    # - name: Run integration tests
    #   if: ${{ inputs.integration-tests == 'true' }}
    #   shell: bash
    #   run: |
    #     cd build/tests/integrationtests/
    #     chmod a+x ./TiGL-integrationtests
    #     ./TiGL-integrationtests --gtest_shuffle --gtest_output=xml:integration_test_results.xml
