name: "Create a Release"

description: "This action drafts a Github release, adds the release notes and windows and mac os artifacts and creates PRs at geoml-conda and the geoml website"

inputs:
  GH_TOKEN:
    description: 'A Github PAT'
    required: true

runs:

  using: "composite"

  steps:

    - uses: actions/checkout@v4

    - name: Split Release Description from Changelog
      shell: bash -l {0}
      run: |
        csplit -z ChangeLog.md /"Version "/ {1}
        mv xx01 release_description.md
        rm xx*

    - name: Read Release Description from splitted Changelog
      id: changelog
      uses: juliangruber/read-file-action@v1
      with:
        path: ./release_description.md

    - name: Parse version
      shell: bash -l {0}
      run: |
        version=`echo $github_ref | cut -c 12-`
        echo $version
        echo "version=$version" >> $GITHUB_ENV
      env:
         github_ref: ${{ github.ref }}
         
    - name: download Win64 package Build artifact
      uses: actions/download-artifact@v4
      with:
        name: win-package
        
    - name: download Win64 installer Build artifact
      uses: actions/download-artifact@v4
      with:
        name: win-installer
         
    - name: download MacOS package Build artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-package
        
    - name: download html-documentation
      uses: actions/download-artifact@v4
      with:
        name: html-documentation
        path: html-documentation

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: geoml ${{ env.version }}
        body: ${{ steps.changelog.outputs.content  }}
        draft: true
        prerelease: false
        token: ${{ inputs.GH_TOKEN }}
        files: |
          win-installer/geoml-${{ env.version }}-win64.exe
          win-package/geoml-${{ env.version }}-win64.zip
          macos-package/geoml-${{ env.version }}-Darwin.dmg

    - name: Checkout geoml-website repo
      uses: actions/checkout@v4
      with:
        repository: DLR-SC/geoml-website
        path: geoml-website

    - name: Add documentation to website
      shell: bash -l {0}
      run: |
        cd geoml-website/content
        rm -rf doc/latest/*
        mkdir -p doc/latest
        mkdir -p doc/${{ env.version }}
        cp -r ../../html-documentation/* doc/latest/
        cp -r ../../html-documentation/* doc/${{ env.version }}/
        cd pages
        today=`date +'%Y-%m-%d %H:%M'`
        sed -i s/"^Date:.*"/"Date: $today"/g 4_Documentation.md
        prevver=`grep "Latest Release" 4_Documentation.md | grep -Eo "[0-9]{1,}.[0-9].{1,}[0-9]{1,}"`
        csplit -z 4_Documentation.md /"Latest Release"/
        mv xx00 4_Documentation.md
        echo " - [Latest Release (geoml ${{ env.version }})](../doc/latest/index.html)" >> 4_Documentation.md
        echo " - [geoml $prevver](../doc/$prevver/index.html)" >> 4_Documentation.md
        tail -n +2 xx01 >> 4_Documentation.md
        rm xx01


    - name: Create Pull Request at DLR-SC/geoml-website
      uses: peter-evans/create-pull-request@v5
      with:
        path: geoml-website
        title: Add documentation for geoml ${{ env.version }}
        body: There has been a new release over at DLR-SC/geoml. We should add the latest documentation to our website.
        branch: add-geoml-${{ env.version }}-documentation
        commit-message: add documentation for geoml ${{ env.version }}
        token: ${{ inputs.GH_TOKEN }}

    - name: Checkout geoml-conda repo
      uses: actions/checkout@v4
      with:
        repository: DLR-SC/geoml-conda
        path: geoml-conda

    - name: Bump version of geoml3 conda recipe and reset build number
      shell: bash -l {0}
      run: |
        sed -i s/"version = \".*\""/"version = \"${{ env.version }}\""/g geoml-conda/geoml3/meta.yaml
        sed -i s/"number: .*"/"number: 0"/g geoml-conda/geoml3/meta.yaml
        git diff

    - name: Create Pull Request at DLR-SC/geoml-conda
      uses: peter-evans/create-pull-request@v5
      with:
        path: geoml-conda
        title: Bump geoml3 version to ${{ env.version }}
        body: There has been a new release over at DLR-SC/geoml. We should create new conda packages!
        branch: bump-geoml3-version
        commit-message: bump geoml3 version to ${{ env.version }}
        token: ${{ inputs.GH_TOKEN }}
