name: "Linux Tests"

description: "Test geoml on Linux"

inputs:

  build-artifact:
    description: "Name of the build artifact that contains the unit test binary."
    required: true

  coverage:
    description: "Create coverage report (true or false)"
    required: false
    default: false

  codecov_token:
    description: 'CodeCov token needed to publish coverage report on codecov'
    required: true

  unit-tests:
    description: "Set to true to run geoml unit tests (true or false)"
    required: false
    default: true

  api-tests:
    description: "Set to true to run geoml api tests (true or false)"
    required: false
    default: true


runs:

  using: "composite"

  steps:

    - name: Install lcov
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lcov
        
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: geoml-bld
        environment-file: environment.yml
        auto-activate-base: false

    - name: Download build directory
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}

    - name: extract build archive
      shell: bash
      run: |
        tar -xzf build.tar.gz

    - name: Run unit tests
      if: ${{ inputs.unit-tests == 'true' }}
      shell: bash
      run: |
        cd build/tests/unittests/
        ./geoml-unittests --gtest_shuffle --gtest_output=xml:unit_test_results.xml

    - name: Run api tests
      if: ${{ inputs.api-tests == 'true' }}
      shell: bash
      run: |
        cd build/tests/apitests/
        ./geoml-apitest --gtest_shuffle --gtest_output=xml:api_test_results.xml

    - name: Generate coverage report
      if: ${{ inputs.coverage == 'true' }}
      shell: bash
      run: |
        cd build
        cmake --build . --target coverage-unittests/fast
        cmake --build . --target coverage-apitests/fast

    - name: Publish coverage report of unittests to codecov.io (ubuntu debug)
      if: ${{ inputs.coverage == 'true' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./build/tests/unittests/coverageReport-unit.info
        token: ${{ inputs.codecov_token }}
        codecov_yml_path: codecov.yml
        disable_search: true
        verbose: true
        flags: unittests

    - name: Publish coverage report of api-tests to codecov.io (ubuntu debug)
      if: ${{ inputs.coverage == 'true' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./build/tests/apitests/coverageReport-api.info
        token: ${{ inputs.codecov_token }}
        codecov_yml_path: codecov.yml
        disable_search: true
        verbose: true
        flags: api-tests

